[air_quality]
port = 9000
description = "Monitors and reports air quality levels in different areas"
dependencies = []
enabled = false
pid = 6794
auto_start = true
last_updated = "2024-12-08T18:26:55.146672"

[chatbot_llm]
port = 9001
description = "LLM-based chatbot service for IIIT Companion"
dependencies = []
enabled = false
pid = 5669
auto_start = true
last_updated = "2024-12-08T18:26:55.147727"

[crowd_monitor]
port = 9002
description = "Tracks and reports real-time crowd density at various locations"
dependencies = []
enabled = false
pid = 5670
auto_start = false
last_updated = "2024-12-08T18:26:55.148364"

[event_notifier]
port = 9003
description = "Sends notifications about upcoming events, shows, and festivals"
dependencies = []
enabled = false
pid = 5671
auto_start = true
last_updated = "2024-12-08T18:26:55.148698"

[exhibition_tracker]
port = 9004
description = "Tracks and notifies users about ongoing and upcoming exhibitions"
dependencies = []
enabled = false
pid = 5672
auto_start = false
last_updated = "2024-12-08T18:26:55.149614"

[historical_info]
port = 9005
description = "Provides historical and cultural information about monuments and sites"
dependencies = []
enabled = false
pid = 5673
auto_start = false
last_updated = "2024-12-08T18:26:55.150332"

[restaurant_finder]
port = 9006
description = "Recommends restaurants based on cuisine preferences and location"
dependencies = []
enabled = false
pid = 5674
auto_start = false
last_updated = "2024-12-08T18:26:55.150704"

[ticket_purchase]
port = 9007
description = "Enables online ticket purchases for attractions and events"
dependencies = []
enabled = false
pid = 5675
auto_start = false
last_updated = "2024-12-08T18:26:55.151073"

[travel_options]
port = 9008
description = "Provides intelligent transportation options and routes to tourist destinations with context-aware recommendations"
dependencies = []
enabled = false
pid = 5676
auto_start = false
last_updated = "2024-12-08T18:26:55.151421"

[water_quality]
port = 9009
description = "Tracks water quality in lakes and other water bodies"
dependencies = []
enabled = false
pid = 5677
auto_start = false
last_updated = "2024-12-08T18:26:55.151740"
