[air_quality]
port = 9000
description = "Monitors and reports air quality levels in different areas"
dependencies = []
enabled = false
pid = 38371
last_updated = "2024-12-08T19:51:47.469537"

[chatbot_llm]
port = 9001
description = "LLM-based chatbot service for IIIT Companion"
dependencies = []
enabled = false
pid = 38372
last_updated = "2024-12-08T19:51:47.471210"

[crowd_monitor]
port = 9002
description = "Tracks and reports real-time crowd density at various locations"
dependencies = []
enabled = false
pid = 38373
last_updated = "2024-12-08T19:51:47.472899"

[event_notifier]
port = 9003
description = "Sends notifications about upcoming events, shows, and festivals"
dependencies = []
enabled = false
pid = 38374
last_updated = "2024-12-08T19:51:47.474030"

[exhibition_tracker]
port = 9004
description = "Tracks and notifies users about ongoing and upcoming exhibitions"
dependencies = []
enabled = false
pid = 38375
last_updated = "2024-12-08T19:51:47.474917"

[historical_info]
port = 9005
description = "Provides historical and cultural information about monuments and sites"
dependencies = []
enabled = false
pid = 38376
last_updated = "2024-12-08T19:51:47.475831"

[restaurant_finder]
port = 9006
description = "Recommends restaurants based on cuisine preferences and location"
dependencies = []
enabled = false
pid = 39484
last_updated = "2024-12-08T19:51:47.476776"

[ticket_purchase]
port = 9007
description = "Enables online ticket purchases for attractions and events"
dependencies = []
enabled = false
pid = 38378
last_updated = "2024-12-08T19:51:47.477644"

[travel_options]
port = 9008
description = "Provides intelligent transportation options and routes to tourist destinations with context-aware recommendations"
dependencies = []
enabled = false
pid = 38379
last_updated = "2024-12-08T19:51:47.478407"

[water_quality]
port = 9009
description = "Tracks water quality in lakes and other water bodies"
dependencies = []
enabled = false
pid = 38380
last_updated = "2024-12-08T19:51:47.479136"
