[air_quality]
port = 9000
description = "Monitors and reports air quality levels in different areas"
dependencies = []

[chatbot_llm]
port = 9001
description = "LLM-based chatbot service for IIIT Companion"
dependencies = []

[crowd_monitor]
port = 9002
description = "Tracks and reports real-time crowd density at various locations"
dependencies = []

[event_notifier]
port = 9003
description = "Sends notifications about upcoming events, shows, and festivals"
dependencies = []

[exhibition_tracker]
port = 9004
description = "Tracks and notifies users about ongoing and upcoming exhibitions"
dependencies = []

[historical_info]
port = 9005
description = "Provides historical and cultural information about monuments and sites"
dependencies = []

[restaurant_finder]
port = 9006
description = "Recommends restaurants based on cuisine preferences and location"
dependencies = []

[ticket_purchase]
port = 9007
description = "Enables online ticket purchases for attractions and events"
dependencies = []

[travel_options]
port = 9008
description = "Provides intelligent transportation options and routes to tourist destinations with context-aware recommendations"
dependencies = []

[water_quality]
port = 9009
description = "Tracks water quality in lakes and other water bodies"
dependencies = []
